version: '3.7'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=testpass
      - MYSQL_PASSWORD=testpass
      - MYSQL_ROOT_PASSWORD=testpass
      - MYSQL_DATABASE=imse_23_ss
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    #  - ./sql/entrypoint.sh:/entrypoint.sh
    ports:
      - 3308:3306
    # entrypoint: ["/entrypoint.sh"]
    # command: cd docker-entrypoint-initdb.d && mysql -uroot -ptestpass < drop.sql && mysql -uroot -ptestpass < mysql_create.sql

  mongodb:
    image: mongo
    volumes:
      - ./mongodb-data:/data/db
    # Add any additional configuration for the MongoDB container here

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 80:80
    tty: true
    stdin_open: true
    volumes:
      - ./php-files:/var/www/html
      - ./apache.conf:/etc/apache2/conf-enabled/custom.conf
