version: '3.7'
services:
  java:
    image: openjdk:17
    volumes:
      - ./java:/java
    working_dir: /java
    #command: ls
    command: java -jar databasefiller.jar

    # Add any additional configuration for the Java container here

  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_USER=testpass
      - MYSQL_PASSWORD=testpass
      - MYSQL_ROOT_PASSWORD=testpass
      - MYSQL_DATABASE=imse_23_ss
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306


  mongodb:
    image: mongo
    volumes:
      - ./mongodb-data:/data/db
    # Add any additional configuration for the MongoDB container here

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - 80:80
    tty: true
    stdin_open: true
    volumes:
      - ./php-files:/var/www/html
      - ./apache.conf:/etc/apache2/conf-enabled/custom.conf

