use imse_23_ss;
DROP VIEW total_sales;
DROP VIEW leasing_options;
DROP TABLE has;
DROP TABLE sells;
DROP TABLE employee;
DROP TABLE car;
DROP TABLE leasing;
DROP TABLE workshop;
DROP TABLE locations;
DROP DATABASE imse_23_ss;